spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.101.206:9876
      bindings:
        output:
          destination: TopicTest
          group: PRODUCER_GROUP_DEMO_2
server:
  port: 9991