pbj:
  databaseurl-port: 127.0.0.1:3306 # 数据库端口
  database-name: db_pbj_test # 数据库名
server:
  port: 6379
spring:
  application:
    name: mybatis # 应用名称
  datasource:
    url: jdbc:mysql://${pbj.databaseurl-port}/${pbj.database-name}?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysqladmin
  redis:
    # 集群配置
    cluster:
      #设置key的生存时间，当key过期时，它会被自动删除；
      expire-seconds: 120
      #设置命令的执行时间，如果超过这个时间，则报错;
      command-timeout: 5000
      #设置redis集群的节点信息，其中namenode为域名解析，通过解析域名来获取相应的地址;
      nodes: 192.168.101.206:7000,192.168.101.206:7001,192.168.101.206:7002,192.168.101.206:7003,192.168.101.206:7004,192.168.101.206:7005
      max-redirects: 3
    # 单机配置
    host: 192.168.101.206
    port: 6379
    database: 0  # 数据库索引，默认0
    timeout: 5000  # 连接超时，单位ms
    jedis:   # 或lettuce, 连接池配置，springboot2.0中使用jedis或者lettuce配置连接池，默认为lettuce连接池
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池分配连接最大阻塞等待时间（阻塞时间到，抛出异常。使用负值表示无限期阻塞）
        max-idle: 8  # 连接池中的最大空闲连接数
        min-idle: 0  # 连接池中的最小空闲连接数
    sentinel:
      master: redis-7000
      nodes: 192.168.101.206:7700,192.168.101.206:7701,192.168.101.206:7702
