pbj:
  databaseurl-port: 127.0.0.1:3306 # 数据库端口
  database-name: db_pbj_test # 数据库名
server:
  port: 6379
spring:
  application:
    name: mybatis # 应用名称
  datasource:
    url: jdbc:mysql://${pbj.databaseurl-port}/${pbj.database-name}?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysqladmin
  redis:
    # 集群配置
    cluster:
      #设置key的生存时间，当key过期时，它会被自动删除；
      expire-seconds: 120
      #设置命令的执行时间，如果超过这个时间，则报错;
      command-timeout: 5000
      #设置redis集群的节点信息，其中namenode为域名解析，通过解析域名来获取相应的地址;
      nodes: 192.168.101.206:7000,192.168.101.206:7001,192.168.101.206:7002,192.168.101.206:7003,192.168.101.206:7004,192.168.101.206:7005
      max-redirects: 3
