spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.101.206:9876
      #        bindings:
      #          input:
      #            consumer:
      #              enable: true
      bindings:
        input:
          destination: TopicTest2
          group: CONSUER_GROUP_DEMO_1

server:
  port: 9992

rocketmq:
  name-server: 192.168.101.206:9876