server:
  port: 8081
  tomcat:
    max-swallow-size: 1MB

management:
  endpoints:
    web:
      base-path: /actuator  # /actuator # Actuator 提供的 API 接口的根目录
      exposure:
        include: '*'  # 需要开放的端点
        exclude:   # 需要排除的端点

spring:
  profiles:
    active: test
  servlet:
    multipart:
      # 默认支持文件上传
      enabled: true
      # 最大支持文件大小
      max-file-size: 50MB
      # 最大支持请求大小
      max-request-size: 100MB
      # 文件支持写入磁盘
      file-size-threshold: 0
      # 上传文件的临时目录
      location: classpath:/file
  jpa:
    # 数据库类型
    database: mysql
    #打印SQL
    show-sql: true
    hibernate:
      ddl-auto: update  #第一次启动创建表，之后修改为update
  thymeleaf:
    # 是否启用
    enabled: true
    # 模板编码
    encoding: UTF-8
    # 模板模式
    mode: HTML5
    # 模板存放路径
    prefix: classpath:/templates/
    # 模板后缀
    suffix: .html
    # 启用缓存，建议生产开启
    cache: false
    # 校验模板是否存在
    check-template-location: true
    # Content-type值
    servlet:
      content-type: text/html
    # 加配置静态资源
    resources:
      static-locations: classpath:/static/
  mail:
    host: smtp.qq.com
    port: 25
    username: 743545369@qq.com
    password: ubvfniugswaebcbb
    default-encoding: UTF-8

mail:
  # 以谁来发送邮件
  fromMail:
    addr: 743545369@qq.com

pbj:
  file:
    path: D:\tmp\file
    extension: .gif,.jpeg,.png,.jpg,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.pdf,.txt,.rar,.tif

#配置Mybatis
mybatis:
  ## 进行mysql多数据源
  type-aliases-package: cn.pbj.demo2020.ssm.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名转换，如：Table(create_time) -> Entity(createTime)。不需要我们关心怎么进行字段匹配，mybatis会自动识别`大写字母与下划线`
    map-underscore-to-camel-case: true

#打印SQL日志
logging:
  level:
    cn.pbj.demo2020.ssm.dao.*: DEBUG
